In [1]:
import VASPsol as vs
import os
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
# lets make a directory ../shape_animation_data/ if it doesn't exist
if not os.path.exists('../shape_animation_data/'):
    os.makedirs('../shape_animation_data/')


In [3]:
# lets copy the files in ../grid_search_calculations/0061tet/ to ../shape_animation_data/
fname = '0008noc'
files = os.listdir('../grid_search_calculations' + '/' + fname + '/')
for file in files:
    if os.path.isfile('../grid_search_calculations'+ '/' + fname + '/' +file):
        os.system('cp ../grid_search_calculations'+ '/' + fname + '/' + file+' ../shape_animation_data/')

In [4]:
client, cluster = vs.ef.dask_workers(32, 4, 4, burst=False)
client

/home/ericfonseca/.local/lib/python3.10/site-packages/dask_jobqueue-0.8.1-py3.10.egg/dask_jobqueue/core.py:255: FutureWarning: job_extra has been renamed to job_extra_directives. You are still using it (even if only set to []; please also check config files). If you did not set job_extra_directives yet, job_extra will be respected for now, but it will be removed in a future release. If you already set job_extra_directives, job_extra is ignored and you can remove it.
  warnings.warn(warn, FutureWarning)
/home/ericfonseca/.local/lib/python3.10/site-packages/dask_jobqueue-0.8.1-py3.10.egg/dask_jobqueue/slurm.py:49: FutureWarning: project has been renamed to account as this kwarg was used wit -A option. You are still using it (please also check config files). If you did not set account yet, project will be respected for now, but it will be removed in a future release. If you already set account, project is ignored and you can remove it.
  warnings.warn(warn, FutureWarning)
/home/ericfonsec

<Client: 'tcp://10.13.55.10:39694' processes=0 threads=0, memory=0 B>

In [5]:
client

<Client: 'tcp://10.13.55.10:39694' processes=0 threads=0, memory=0 B>

In [7]:
NC_K_default = 0.0025
TAU_K_default = 0.000525
SIGMA_K_default = 0.6
NC_KPOINTS = np.linspace(0.001, 0.005, 20)
SIGMA_KPOINTS = np.ones((1, 20))*SIGMA_K_default
TAU_KPOINTS = np.ones((1, 20))
NC_KPOINTS = NC_KPOINTS
TAU_KPOINTS = TAU_KPOINTS*TAU_K_default
SIGMA_KPOINTS, NC_KPOINTS, TAU_KPOINTS 

(array([[0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6,
         0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6]]),
 array([0.001     , 0.00121053, 0.00142105, 0.00163158, 0.00184211,
        0.00205263, 0.00226316, 0.00247368, 0.00268421, 0.00289474,
        0.00310526, 0.00331579, 0.00352632, 0.00373684, 0.00394737,
        0.00415789, 0.00436842, 0.00457895, 0.00478947, 0.005     ]),
 array([[0.000525, 0.000525, 0.000525, 0.000525, 0.000525, 0.000525,
         0.000525, 0.000525, 0.000525, 0.000525, 0.000525, 0.000525,
         0.000525, 0.000525, 0.000525, 0.000525, 0.000525, 0.000525,
         0.000525, 0.000525]]))

In [8]:
def calc_solv(directory, NC_K, SIGMA_K, TAU):
    try:
        return vs.calculate_solvent(directory, NSW=0, dict_of_additional_tags={'NC_K': NC_K, 
                                                                               'SIGMA_K': SIGMA_K, 
                                                                               'TAU': TAU,
                                                                               'LRHOB':'TRUE'})
    except:
        return None

In [9]:
vac_job = client.submit(vs.calculate_vacuum, '../shape_animation_data/')
from dask.distributed import progress
progress(vac_job)

VBox()

In [10]:
# submit all the solv jobs
solv_jobs = []
test_solv = client.submit(calc_solv, '../shape_animation_data/' + fname, NC_KPOINTS[0], SIGMA_KPOINTS[0,0], TAU_KPOINTS[0, 0])
progress(test_solv)

VBox()

In [11]:
# submit all the solv jobs
solv_jobs = []
for i in range(NC_KPOINTS.shape[0]):
    for j in range(SIGMA_KPOINTS.shape[0]):
        for k in range(TAU_KPOINTS.shape[1]):
            solv_jobs.append(client.submit(calc_solv, '../shape_animation_data/'+ fname, NC_KPOINTS[i], SIGMA_KPOINTS[0, j], TAU_KPOINTS[0, k]))
progress(solv_jobs)

VBox()

In [12]:
# get all the jobs on the client
all_jobs = [vac_job, test_solv,  *solv_jobs]
progress(all_jobs)

VBox()

In [13]:
solv_jobs = client.gather(solv_jobs)
solv_df = pd.concat([i.ml_df for i in solv_jobs if i is not None])
# save solv_df with the date
import time
fname = time.strftime("%Y%m%d")
solv_df_name = 'solv_df_' + fname + '.csv'
# save
solv_df.to_csv(solv_df_name)

KeyboardInterrupt: 